import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-blue-600 p-4">
          <ul className="flex justify-between items-center text-white">
            <div className="flex gap-4">
              <li>
                <Link href={`/blog`} className="text-lg">
                  Posts
                </Link>
              </li>
              <li>
                <Link href="/dynamic" className="text-lg">
                  Dynamic
                </Link>
              </li>
              <li>
                <Link href="/static" className="text-lg">
                  Static
                </Link>
              </li>
            </div>
          </ul>
        </nav>
        <main className="p-6">{children}</main>
      </body>
    </html>
  );
}
